apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: argo-demo
  labels:
    app.kubernetes.io/name: nginx
    app.revision: 1.0.0
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.revision: 1.0.0
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
